import { CarColours, CarData } from "@ridex/common"

export const carData: CarData = {
  "Maruti Suzuki": [
    "Wagon R",
    "Swift",
    "Baleno",
    "Dzire",
    "Alto",
    "Ertiga",
    "Brezza",
    "Celerio",
    "S-Presso",
    "Ignis",
    "XL6",
    "Fronx",
    "Jimny",
    "Grand Vitara",
    "Ciaz",
    "Alto K10",
    "Eeco",
    "S-Cross",
    "Omni",
    "Zen"
  ],
  "Hyundai": [
    "Creta",
    "i20",
    "Venue",
    "Grand i10 Nios",
    "Verna",
    "Aura",
    "Alcazar",
    "Tucson",
    "Exter",
    "i10",
    "Kona Electric",
    "iONIQ 5",
    "Elantra",
    "Santro",
    "Xcent",
    "Eon",
    "Accent",
    "Getz",
    "Sonata",
    "Terracan"
  ],
  "Tata Motors": [
    "Nexon",
    "Punch",
    "Tiago",
    "Altroz",
    "Harrier",
    "Safari",
    "Tigor",
    "Nexon EV",
    "Tiago EV",
    "Tigor EV",
    "Zest",
    "Bolt",
    "Indica",
    "Indigo",
    "Sumo",
    "Hexa",
    "Aria",
    "Vista",
    "Manza",
    "Nano"
  ],
  "Mahindra": [
    "Scorpio",
    "Bolero",
    "XUV700",
    "Thar",
    "XUV300",
    "Marazzo",
    "KUV100",
    "Alturas G4",
    "Verito",
    "eVerito",
    "TUV300",
    "Xylo",
    "Quanto",
    "NuvoSport",
    "Rexton",
    "Logan",
    "Commander",
    "Armada",
    "Classic",
    "Maxx"
  ],
  "Toyota": [
    "Innova Crysta",
    "Fortuner",
    "Glanza",
    "Urban Cruiser Hyryder",
    "Camry",
    "Hilux",
    "Vellfire",
    "Yaris",
    "Etios",
    "Corolla Altis",
    "Land Cruiser",
    "Prius",
    "Avanza",
    "Rush",
    "Qualis",
    "Platinum Etios",
    "Innova Hycross",
    "Etios Cross",
    "Supra",
    "C-HR"
  ],
  "Kia": [
    "Seltos",
    "Sonet",
    "Carens",
    "Carnival",
    "EV6",
    "Sportage",
    "Sorento",
    "Stinger",
    "Rio",
    "Picanto",
    "Ceed",
    "Optima",
    "Soul",
    "Telluride",
    "Niro",
    "K900",
    "Cadenza",
    "Cerato",
    "Mohave",
    "Borrego"
  ],
  "Honda": [
    "City",
    "Amaze",
    "WR-V",
    "Jazz",
    "Civic",
    "Accord",
    "CR-V",
    "BR-V",
    "Brio",
    "Mobilio",
    "HR-V",
    "Pilot",
    "Odyssey",
    "Fit",
    "Insight",
    "Passport",
    "Ridgeline",
    "Element",
    "Prelude",
    "S2000"
  ],
  "MG": [
    "Hector",
    "Astor",
    "Gloster",
    "ZS EV",
    "Comet EV",
    "MG5 EV",
    "MG6",
    "MG3",
    "MG7",
    "Marvel R",
    "EZS",
    "RX5",
    "HS",
    "GT",
    "TF",
    "GS",
    "ZS",
    "Extender",
    "RC-6",
    "Baojun 530"
  ],
  "Volkswagen": [
    "Polo",
    "Vento",
    "Taigun",
    "Virtus",
    "Tiguan",
    "Passat",
    "Jetta",
    "Beetle",
    "Golf",
    "T-Roc",
    "Touareg",
    "Arteon",
    "ID.4",
    "ID.3",
    "ID. Buzz",
    "Up!",
    "Scirocco",
    "Amarok",
    "Atlas",
    "CC"
  ],
  "Renault": [
    "Kwid",
    "Triber",
    "Kiger",
    "Duster",
    "Captur",
    "Lodgy",
    "Scala",
    "Pulse",
    "Fluence",
    "Logan",
    "Clio",
    "Megane",
    "Talisman",
    "Koleos",
    "Zoe",
    "Sandero",
    "Symbol",
    "Espace",
    "Laguna",
    "Modus"
  ]
}

export const carColoursData: CarColours = [
  { "name": "White", "hex": "#FFFFFF" },
  { "name": "Black", "hex": "#000000" },
  { "name": "Grey", "hex": "#808080" },
  { "name": "Silver", "hex": "#C0C0C0" },
  { "name": "Blue", "hex": "#0000FF" },
  { "name": "Red", "hex": "#FF0000" },
  { "name": "Green", "hex": "#008000" },
  { "name": "Yellow", "hex": "#FFFF00" },
  { "name": "Gold", "hex": "#D4AF37" },
  { "name": "Maroon", "hex": "#800000" },
  { "name": "Beige", "hex": "#F5F5DC" },
  { "name": "Purple", "hex": "#800080" },
  { "name": "Orange", "hex": "#FFA500" }
]